/**
 * ArtifactViewer Component
 *
 * Displays and manages artifacts generated from dual AI collaboration.
 * Features: Markdown preview, edit mode, save to documents, commit to GitHub.
 */

import React, { useState, useCallback } from 'react';
import {
  FileText,
  Edit3,
  Eye,
  Save,
  Github,
  Copy,
  Check,
  Download,
  Loader2,
  AlertCircle,
  CheckCircle,
  Info,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Input } from '@/components/ui/input';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogFooter,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import ReactMarkdown from 'react-markdown';
import { toast } from 'sonner';
import { github } from '@/api/github';
import { checkAnalysisFreshness } from '@/api/repositoryAnalyzer';
import { cn } from '@/lib/utils';

/**
 * ArtifactViewer component for viewing and managing generated artifacts
 */
const ArtifactViewer = ({
  artifact,
  repoFullName,
  onSaveToDocuments,
  onAnalyzeCompleteness,
  isSaving = false,
}) => {
  const [isEditing, setIsEditing] = useState(false);
  const [editedContent, setEditedContent] = useState(artifact?.content || '');
  const [copied, setCopied] = useState(false);
  const [isCommitting, setIsCommitting] = useState(false);
  const [commitDialogOpen, setCommitDialogOpen] = useState(false);
  const [commitForm, setCommitForm] = useState({
    fileName: 'ai-collaboration-plan.md',
    commitMessage: 'docs: add AI collaboration plan',
    createPR: true,
  });
  const [safetyStatus, setSafetyStatus] = useState({ state: 'unknown', details: null });

  // Parse repo full name
  const [owner, repo] = repoFullName?.split('/') || [];

  // Handle copy to clipboard
  const handleCopy = useCallback(async () => {
    try {
      await navigator.clipboard.writeText(editedContent || artifact?.content || '');
      setCopied(true);
      toast.success('Copied to clipboard');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy');
    }
  }, [editedContent, artifact?.content]);

  // Handle save edits
  const handleSaveEdits = useCallback(() => {
    setIsEditing(false);
    toast.success('Changes saved');
  }, []);

  // Handle download as markdown file
  const handleDownload = useCallback(() => {
    const content = editedContent || artifact?.content || '';
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ai-collaboration-artifact.md';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Downloaded as markdown file');
  }, [editedContent, artifact?.content]);

  // Handle commit to GitHub
  const handleCommitToGitHub = useCallback(async () => {
    if (!owner || !repo) {
      toast.error('No repository selected');
      return;
    }

    setIsCommitting(true);

    try {
      // Safety Check: Verify analysis freshness
      const repoData = await github.getRepo(owner, repo);
      const freshness = await checkAnalysisFreshness(repoData.id, owner, repo);
      
      if (freshness.needsRefresh && freshness.reason === 'new_commits') {
        const proceed = window.confirm(
          `CAUTION: The repository has changed since the last AI analysis. Your artifact might be based on stale code. \n\nLast analyzed SHA: ${freshness.lastSha.substring(0, 7)}\nCurrent main SHA: ${freshness.currentSha.substring(0, 7)}\n\nDo you want to proceed anyway?`
        );
        if (!proceed) {
          setIsCommitting(false);
          return;
        }
      }

      const content = editedContent || artifact?.content || '';
      const timestamp = Date.now();
      const branchName = `feature/ai-collab-${timestamp}`;

      // Get default branch
      const defaultBranch = await github.getDefaultBranch(owner, repo);

      // Create feature branch
      await github.createBranch(owner, repo, branchName, defaultBranch);
      toast.success(`Created branch: ${branchName}`);

      // Create/update file in the new branch
      const filePath = `docs/${commitForm.fileName}`;
      await github.createOrUpdateFile(
        owner,
        repo,
        filePath,
        content,
        commitForm.commitMessage,
        branchName
      );
      toast.success(`File committed to ${branchName}`);

      // Optionally create PR
      if (commitForm.createPR) {
        const prBody = `## AI Collaboration Artifact

This document was generated using Proflow's Dual-AI Collaboration feature.

### Generated by:
- **Gemini** (Rapid Architect)
- **Claude Opus 4.5** (Deep Thinker)

### Summary
${content.substring(0, 500)}${content.length > 500 ? '...' : ''}

---
Generated with [Proflow](https://proflow.dev)`;

        const pr = await github.createPullRequest(
          owner,
          repo,
          `docs: ${commitForm.fileName.replace('.md', '')}`,
          prBody,
          branchName,
          defaultBranch
        );

        toast.success('Pull request created!');
        window.open(pr.html_url, '_blank');
      }

      setCommitDialogOpen(false);
    } catch (error) {
      console.error('GitHub commit error:', error);
      toast.error(`Failed: ${error.message}`);
    } finally {
      setIsCommitting(false);
    }
  }, [owner, repo, editedContent, artifact?.content, commitForm]);

  if (!artifact) {
    return (
      <div className="flex flex-col items-center justify-center h-full text-center text-gray-400 p-8">
        <FileText className="w-16 h-16 mb-4 opacity-30" />
        <p className="text-lg font-medium">No artifact generated yet</p>
        <p className="text-sm mt-2">
          Use the dual AI collaboration to generate a document
        </p>
      </div>
    );
  }

  const content = isEditing ? editedContent : artifact.content;

  return (
    <div className="flex flex-col h-full bg-background border rounded-lg overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b bg-card">
        <div className="flex items-center gap-2">
          <FileText className="w-5 h-5 text-primary" />
          <div>
            <h3 className="text-sm font-semibold">Generated Artifact</h3>
            <p className="text-xs text-muted-foreground">
              {new Date(artifact.generatedAt).toLocaleString()}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Toggle Edit/Preview */}
          <Button
            variant="outline"
            size="sm"
            onClick={() => setIsEditing(!isEditing)}
          >
            {isEditing ? (
              <>
                <Eye className="w-4 h-4 mr-2" />
                Preview
              </>
            ) : (
              <>
                <Edit3 className="w-4 h-4 mr-2" />
                Edit
              </>
            )}
          </Button>

          {/* Save Edits (only in edit mode) */}
          {isEditing && (
            <Button variant="outline" size="sm" onClick={handleSaveEdits}>
              <Save className="w-4 h-4 mr-2" />
              Save
            </Button>
          )}

          {/* Copy */}
          <Button variant="outline" size="icon" onClick={handleCopy}>
            {copied ? (
              <Check className="w-4 h-4 text-green-500" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
          </Button>

          {/* Download */}
          <Button variant="outline" size="icon" onClick={handleDownload}>
            <Download className="w-4 h-4" />
          </Button>

          {/* Analyze for Completeness */}
          {onAnalyzeCompleteness && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => onAnalyzeCompleteness(content)}
            >
              <CheckCircle className="w-4 h-4 mr-2" />
              Analyze
            </Button>
          )}

          {/* Save to Documents */}
          {onSaveToDocuments && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => onSaveToDocuments(content, artifact?.title || 'AI Collaboration Document')}
              disabled={isSaving}
            >
              {isSaving ? (
                <>
                  <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                  Saving...
                </>
              ) : (
                <>
                  <Save className="w-4 h-4 mr-2" />
                  Save to Docs
                </>
              )}
            </Button>
          )}

          {/* Commit to GitHub */}
          {repoFullName && (
            <Dialog open={commitDialogOpen} onOpenChange={setCommitDialogOpen}>
              <DialogTrigger asChild>
                <Button size="sm" className="bg-gray-800 hover:bg-gray-700">
                  <Github className="w-4 h-4 mr-2" />
                  Commit
                </Button>
              </DialogTrigger>
              <DialogContent>
                <DialogHeader>
                  <DialogTitle>Commit to GitHub</DialogTitle>
                  <DialogDescription>
                    Create a feature branch and commit this artifact to {repoFullName}
                  </DialogDescription>
                </DialogHeader>

                <div className="space-y-4 py-4">
                  <div className="space-y-2">
                    <Label htmlFor="fileName">File name</Label>
                    <Input
                      id="fileName"
                      value={commitForm.fileName}
                      onChange={(e) =>
                        setCommitForm((prev) => ({
                          ...prev,
                          fileName: e.target.value,
                        }))
                      }
                      placeholder="my-plan.md"
                    />
                    <p className="text-xs text-muted-foreground">
                      Will be saved to docs/{commitForm.fileName}
                    </p>
                  </div>

                  <div className="space-y-2">
                    <Label htmlFor="commitMessage">Commit message</Label>
                    <Input
                      id="commitMessage"
                      value={commitForm.commitMessage}
                      onChange={(e) =>
                        setCommitForm((prev) => ({
                          ...prev,
                          commitMessage: e.target.value,
                        }))
                      }
                      placeholder="docs: add feature plan"
                    />
                  </div>

                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="createPR"
                      checked={commitForm.createPR}
                      onChange={(e) =>
                        setCommitForm((prev) => ({
                          ...prev,
                          createPR: e.target.checked,
                        }))
                      }
                      className="rounded"
                    />
                    <Label htmlFor="createPR" className="text-sm">
                      Create pull request automatically
                    </Label>
                  </div>
                </div>

                <Alert>
                  <AlertCircle className="h-4 w-4" />
                  <AlertDescription>
                    A new branch will be created. Your changes won't affect the main branch directly.
                  </AlertDescription>
                </Alert>

                {artifact?.generatedAt && (
                   <Alert variant="outline" className="border-blue-200 bg-blue-50/30 text-xs">
                     <Info className="h-3 w-3 mr-2" />
                     Artifact generated at {new Date(artifact.generatedAt).toLocaleTimeString()}
                   </Alert>
                )}

                <DialogFooter>
                  <Button
                    variant="outline"
                    onClick={() => setCommitDialogOpen(false)}
                  >
                    Cancel
                  </Button>
                  <Button
                    onClick={handleCommitToGitHub}
                    disabled={isCommitting || !commitForm.fileName}
                    className="bg-gray-800 hover:bg-gray-700"
                  >
                    {isCommitting ? (
                      <>
                        <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                        Committing...
                      </>
                    ) : (
                      <>
                        <Github className="w-4 h-4 mr-2" />
                        Commit & Push
                      </>
                    )}
                  </Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          )}
        </div>
      </div>

      {/* Content Area */}
      <div className="flex-1 overflow-hidden">
        {isEditing ? (
          <Textarea
            value={editedContent}
            onChange={(e) => setEditedContent(e.target.value)}
            className="w-full h-full resize-none border-0 rounded-none font-mono text-sm"
            placeholder="Edit your artifact..."
          />
        ) : (
          <ScrollArea className="h-full p-6">
            <div className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown>{content}</ReactMarkdown>
            </div>
          </ScrollArea>
        )}
      </div>

      {/* Footer with stats */}
      <div className="flex items-center justify-between px-4 py-2 border-t bg-muted/30 text-xs text-muted-foreground">
        <div className="flex items-center gap-4">
          <span>
            {content.split(/\s+/).filter(Boolean).length} words
          </span>
          <span>
            {content.length} characters
          </span>
        </div>
        <div className="flex items-center gap-2">
          <Badge variant="outline" className="text-[10px]">
            Gemini: {artifact.sources?.geminiMessages || 0} msgs
          </Badge>
          <Badge variant="outline" className="text-[10px]">
            Claude: {artifact.sources?.claudeMessages || 0} msgs
          </Badge>
        </div>
      </div>
    </div>
  );
};

export default ArtifactViewer;
