/**
 * Formats a bug report into a Claude-ready prompt
 */
export function formatBugReportPrompt({
  description,
  route,
  componentPath,
  componentName,
  selector,
  dimensions,
  viewportSize,
  requestedChange,
  hasAnnotatedScreenshot,
  annotationCount = 0
}) {
  // Extract page name from route
  const pageName = getPageNameFromRoute(route);

  // Build the prompt
  let prompt = `Fix this issue on the ${pageName} page:\n\n`;

  // Problem description
  prompt += `**Problem**: ${description || '[No description provided]'}\n\n`;

  // Location details
  prompt += `**Location**:\n`;
  prompt += `- Page: ${route}\n`;

  if (componentPath) {
    prompt += `- Component: ${componentPath}\n`;
  }

  if (componentName && componentName !== componentPath) {
    prompt += `- Component Name: ${componentName}\n`;
  }

  if (selector) {
    prompt += `- Element: \`${selector}\`\n`;
  }

  if (dimensions && (dimensions.width || dimensions.height)) {
    prompt += `- Element Size: ${dimensions.width}x${dimensions.height}px\n`;
  }

  prompt += '\n';

  // Visual reference
  if (hasAnnotatedScreenshot) {
    prompt += `**Visual Reference**: See the annotated screenshot above - `;
    if (annotationCount > 0) {
      prompt += `${annotationCount} annotation${annotationCount > 1 ? 's' : ''} highlight${annotationCount > 1 ? '' : 's'} the problem area${annotationCount > 1 ? 's' : ''}.\n\n`;
    } else {
      prompt += `the screenshot shows the current state.\n\n`;
    }
  }

  // Viewport info
  prompt += `**Viewport**: ${viewportSize.width}x${viewportSize.height}\n\n`;

  // Requested change
  prompt += `**Requested Change**: ${requestedChange || '[No specific change requested]'}\n`;

  // Footer
  prompt += `\n---\n*Generated by Visual Bug Reporter*`;

  return prompt;
}

/**
 * Extract a human-readable page name from a route
 */
function getPageNameFromRoute(route) {
  if (!route || route === '/') {
    return 'Home';
  }

  // Remove leading slash and split by slashes
  const parts = route.replace(/^\//, '').split('/');

  // Get the first meaningful part
  const firstPart = parts[0] || 'Home';

  // Convert to title case and handle common patterns
  return firstPart
    .replace(/([A-Z])/g, ' $1') // Add space before capital letters
    .replace(/[-_]/g, ' ')      // Replace dashes and underscores with spaces
    .replace(/\b\w/g, c => c.toUpperCase()) // Capitalize first letter of each word
    .trim();
}

/**
 * Format a compact summary for the copy button tooltip
 */
export function formatPromptSummary({
  route,
  componentName,
  selector,
  hasDescription,
  hasRequestedChange
}) {
  const parts = [];

  if (route) parts.push(`Page: ${route}`);
  if (componentName) parts.push(`Component: ${componentName}`);
  if (selector) parts.push(`Element: ${selector.substring(0, 30)}...`);
  if (hasDescription) parts.push('Description');
  if (hasRequestedChange) parts.push('Requested change');

  return parts.join(' | ');
}
